/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FindMyService {
    'categories': string;
    'council': boolean;
    'layers': string;
  }
  interface MapGallery {
    'id': string;
  }
  interface WebMap {
    'address': string;
    'basemap': string;
    'basemapselect': boolean;
    'center': string;
    'collapsewidgets': boolean;
    'dark': boolean;
    'dockposition': string;
    'expandedwidget': string;
    'filter': boolean;
    'highlight': boolean;
    'layerlist': boolean;
    'legend': boolean;
    'mapId': string;
    'navigate': boolean;
    'popup': boolean;
    'popupdocked': boolean;
    'querylayer': string;
    'querywhere': string;
    'scene': boolean;
    'sceneId': string;
    'search': boolean;
    'zoom': number;
  }
}

declare global {


  interface HTMLFindMyServiceElement extends Components.FindMyService, HTMLStencilElement {}
  var HTMLFindMyServiceElement: {
    prototype: HTMLFindMyServiceElement;
    new (): HTMLFindMyServiceElement;
  };

  interface HTMLMapGalleryElement extends Components.MapGallery, HTMLStencilElement {}
  var HTMLMapGalleryElement: {
    prototype: HTMLMapGalleryElement;
    new (): HTMLMapGalleryElement;
  };

  interface HTMLWebMapElement extends Components.WebMap, HTMLStencilElement {}
  var HTMLWebMapElement: {
    prototype: HTMLWebMapElement;
    new (): HTMLWebMapElement;
  };
  interface HTMLElementTagNameMap {
    'find-my-service': HTMLFindMyServiceElement;
    'map-gallery': HTMLMapGalleryElement;
    'web-map': HTMLWebMapElement;
  }
}

declare namespace LocalJSX {
  interface FindMyService {
    'categories'?: string;
    'council'?: boolean;
    'layers'?: string;
  }
  interface MapGallery {
    'id'?: string;
  }
  interface WebMap {
    'address'?: string;
    'basemap'?: string;
    'basemapselect'?: boolean;
    'center'?: string;
    'collapsewidgets'?: boolean;
    'dark'?: boolean;
    'dockposition'?: string;
    'expandedwidget'?: string;
    'filter'?: boolean;
    'highlight'?: boolean;
    'layerlist'?: boolean;
    'legend'?: boolean;
    'mapId'?: string;
    'navigate'?: boolean;
    'popup'?: boolean;
    'popupdocked'?: boolean;
    'querylayer'?: string;
    'querywhere'?: string;
    'scene'?: boolean;
    'sceneId'?: string;
    'search'?: boolean;
    'zoom'?: number;
  }

  interface IntrinsicElements {
    'find-my-service': FindMyService;
    'map-gallery': MapGallery;
    'web-map': WebMap;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'find-my-service': LocalJSX.FindMyService & JSXBase.HTMLAttributes<HTMLFindMyServiceElement>;
      'map-gallery': LocalJSX.MapGallery & JSXBase.HTMLAttributes<HTMLMapGalleryElement>;
      'web-map': LocalJSX.WebMap & JSXBase.HTMLAttributes<HTMLWebMapElement>;
    }
  }
}


